/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-125972-ge13b2e00e8-20260805"
#endif /* AVUTIL_FFVERSION_H */
